"""empty message

Revision ID: d16e81d66572
Revises: 
Create Date: 2020-03-17 13:50:39.416809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16e81d66572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('address1', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('telephone_no', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('addresslocation', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers')
    # ### end Alembic commands ###
